package:
  name: cpp_python_hybrid
  version: "0.5.0"


#source:
#  git_url: https://github.com/ilanschnell/bsdiff4.git
#  git_rev: 1.1.4
#  git_depth: 1 # (Defaults to -1/not shallow)


source:
  url: https://github.com/boromir674/toy-recipe/archive/v0.5.tar.gz

requirements:
  build:
    - git
    - gxx_linux-64
  host:
    - python
    - pip
  run:
    - python


#build:
#  number: 3
#  script: "python -m pip install . --no-deps --ignore-installed -vv "

test:
  source_files:
    - tox.ini
    - tests/*
  requires:
    - pytest


about:
  summary: This is a simple package
